# version: '3.8' # últimas versões não exigem a especificacao da versao
# 
networks:
  zabbix-net:
    driver: bridge

volumes:
  mysql-data:
  proxy1-data:
  proxy2-data:
  grafana-data:
  portainer-data:

services:
  mysql:            # Banco de dados MySQL para o Zabbix
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --log_bin_trust_function_creators=1    # somente para versoes anteriores a 6.4 e criacao de schema do banco (deploy)
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"

  grafana:          # Grafana for dashboards
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel, grafana-simple-json-datasource
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - zabbix-net

  zabbix-server:    # Coletor central, conecta no MySQL
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    depends_on:
      - mysql
    ports:
      - "10051:10051"
    networks:
      - zabbix-net

  zabbix-web:       # Interface web acessível via navegador
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.0-latest
    container_name: zabbix-web
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net

  zabbix-proxy1:    # Proxy leve com SQLite3
    image: zabbix/zabbix-proxy-sqlite3:alpine-7.0-latest
    container_name: zabbix-proxy1
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: zabbix-proxy1
    volumes:
      - proxy1-data:/var/lib/zabbix
    depends_on:
      - zabbix-server
    ports:
      - "10052:10051"
    networks:
      - zabbix-net

  zabbix-proxy2:    # Proxy leve com SQLite3
    image: zabbix/zabbix-proxy-sqlite3:alpine-7.0-latest
    container_name: zabbix-proxy2
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: zabbix-proxy2
    volumes:
      - proxy2-data:/var/lib/zabbix
    depends_on:
      - zabbix-server
    ports:
      - "10053:10051"
    networks:
      - zabbix-net

  zabbix-agent1:
    image: zabbix/zabbix-agent:alpine-7.0-latest
    container_name: zabbix_agent1
    environment:
      - ZBX_HOSTNAME=zabbix_agent1
      - ZBX_SERVER_HOST=zabbix-proxy1
      # - ZBX_PASSIVESERVERS="zabbix-proxy1"
      # - ZBX_ACTIVESERVERS="zabbix-proxy1:10052"
    restart: unless-stopped
    networks:
      - zabbix-net

  zabbix-agent2:
    image: zabbix/zabbix-agent:alpine-7.0-latest
    container_name: zabbix_agent2
    environment:
      - ZBX_HOSTNAME=zabbix_agent2
      - ZBX_SERVER_HOST=zabbix-proxy2
      - ZBX_PASSIVESERVERS=zabbix-proxy2
      - ZBX_ACTIVESERVERS=zabbix-proxy2:10053
    restart: unless-stopped
    networks:
      - zabbix-net

  portainer:        # Interface gráfica para gerenciar todos os containers
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - zabbix-net
